### ISSUE TITLE
What is the prob

### ISSUE THREAD

**Issue by thelinuxuser-choice** [taj0023/EtTuS#1]
Scanning 381 ports....
──────────────────────────────────
PORT          STATE        SERVICE
Port 80       OPEN         http
Port 443      OPEN         https
Traceback (most recent call last):
  File "ettus.py", line 49, in <module>
    main()
  File "ettus.py", line 41, in main
    f.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "ettus.py", line 27, in scanner
    s.connect((ip, port))
socket.gaierror: [Errno -3] Temporary failure in name resolution

**Comment by thelinuxuser-choice** [comment]
in widows after upgrade pip it worked but l**_inux is still_**
"pip3 install --upgrade pip"

**Comment by taj0023** [comment]
Hello @thelinuxuser-choice ,
Sorry for the delay, but the possible reasons for this particular error might be :-


1.  It couldn't get service name from the given port.
2.  Slight misconfiguration of `/etc/resolve.conf`.
3.  Presence of firewalls. 
4.  The protocol was provided along with the hostname.


__Possible Workarounds__:

1.  [/etc/resolve.conf or firewalls](https://www.linuxhowto.net/how-to-resolve-temporary-failure-in-name-resolution-issue/)
2.  [getservbyport() stackoverflow](https://stackoverflow.com/questions/40399163/socket-connect-gives-socket-gaierror-errno-11004-getaddrinfo-failed)

**Comment by thelinuxuser-choice** [comment]
thanks @taj0023
